const mongoose=require("mongoose")

const productSchema= new mongoose.Schema({
    description:{
        required:true,
        type:String
    },
    name:{
        required:true,
        type:String
    },
    productImage:{//as image and videos are so heavy to store directly in the format or data type called buffer(data type of mongoDB), so stored in the format of URL generated by cloudServices like AWS through an API
        type:String
    },
    Price:{
        type:Number,
        default:0
    },
    Stock:{
        type:Number,
        default:0
    },
    category:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"category",
        required:true
    },
    owner:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User"
    }
},{timestamps:true})

export const Product=mongoose.model("Product",productSchema)
